#' @title Compute derived clinical variables on a server-side data frame
#' @description Adds \code{USPDGS} (= USPD + USGS) and/or \code{DAS2C}
#'   (= sqrt(SJC28) + 0.6*log1p(CRP)) wherever the required source columns
#'   are available at a given site, via the disclosure-safe server function
#'   \code{compute_derived_variablesDS}, called through
#'   \code{datashield.aggregate} -- the modified data frame is created
#'   server-side as a side effect; only column names come back.
#'
#' Server function called: \code{compute_derived_variablesDS}
#'
#' @param df A character string specifying the name of the server-side data frame.
#' @param newobj A character string specifying the name of the new server-side
#'   object. If NULL, a name is generated by appending \code{"_derived"} to \code{df}.
#' @param datasources A list of \code{\link[DSI]{DSConnection-class}} objects.
#'   If not specified, the default set of connections is used.
#'
#' @return Invisibly returns the name of the newly created server-side object.
#' @export
ds.compute_derived_variables <- function(df, newobj = NULL, datasources = NULL) {

  if (is.null(datasources)) {
    datasources <- datashield.connections_find()
  }

  if (is.null(newobj)) {
    newobj <- paste0(df, "_derived")
  }

  results <- DSI::datashield.aggregate(
    conns = datasources,
    expr  = call("compute_derived_variablesDS", as.symbol(df), newobj)
  )

  for (server in names(results)) {
    computed <- results[[server]]$computed
    if (length(computed) == 0) {
      message("Server ", server, ": no derived variables computed (missing source columns).")
    } else {
      message("Server ", server, ": computed ", paste(computed, collapse = ", "))
    }
  }

  message("Result saved as: '", newobj, "'")
  invisible(newobj)
}
