#' @title Filter columns of a server-side object based on a missingness threshold
#'
#' @description Computes the percentage of missing values for each variable in a distributed
#' data set and optionally removes variables exceeding a user-defined threshold.
#'
#' The function supports two filtering strategies:
#' \itemize{
#'   \item \code{"combined"}: computes a global missingness percentage for each
#'   variable as a weighted average across all servers. The same set of variables
#'   is removed from all servers.
#'   \item \code{"split"}: evaluates missingness independently on each server and
#'   removes server-specific sets of variables.
#' }
#'
#' A missingness table is always displayed. When variables exceed the threshold,
#' they are reported along with their missingness percentages.
#'
#' If no variables exceed the threshold, no filtering is applied and the original
#' data remain unchanged.
#'
#' In addition to being displayed, the underlying missingness table(s) are attached
#' as attributes to the returned value, so they can be retrieved for further use
#' (e.g. plotting) without re-parsing the printed messages. Only the attribute
#' relevant to the chosen \code{type} is populated; the other is \code{NULL}:
#' \itemize{
#'   \item \code{"missing_aggregate"}: populated only when \code{type = "combined"}.
#'   A single \code{data.frame} with variables as row names, one column per server,
#'   and a \code{global} column with the weighted-average missingness percentage.
#'   \item \code{"missing_server"}: populated only when \code{type = "split"}.
#'   A named list of \code{data.frame}s (one per server), each with variables as
#'   row names and a single column containing that server's missingness percentages.
#' }
#'
#' Server-side functions called: \code{check_missing_dataDS} (aggregate),
#' \code{remove_columnsDS}/\code{drop_rows_missingDS} -- both called via
#' \code{datashield.aggregate}, creating the new object server-side via
#' \code{base::assign(newobj, ..., envir=parent.frame())} as a side effect.
#'
#' @param df A character string specifying the name of the input data frame
#' stored on each server.
#' @param threshold A numeric value between 0 and 100 representing the maximum
#' allowed percentage of missing values per variable.
#' @param type A character string specifying the filtering strategy:
#' \code{"combined"} (default) or \code{"split"}.
#' @param remove A logical value indicating whether flagged variables should be
#' acted on at all. If \code{TRUE} (default), the strategy in \code{action} is
#' applied. If \code{FALSE}, variables exceeding the threshold are only
#' identified and returned, without modifying any server-side object.
#' @param action A character string, one of \code{"drop_column"} (default --
#' the flagged VARIABLE is removed for every row, via \code{remove_columnsDS};
#' original behaviour) or \code{"drop_rows"} (the variable is kept, and instead
#' only the ROWS missing on that variable are removed, via
#' \code{drop_rows_missingDS}). Use \code{"drop_rows"} when a variable is too
#' important to drop outright but its missingness is concentrated in a
#' removable subset of rows; use \code{"drop_column"} when the variable itself
#' is unusable across most of the cohort. Ignored if \code{remove = FALSE}.
#' @param preproc_newobj A character string specifying the name of the output
#' server-side object. If \code{NULL}, a name is automatically generated by
#' appending \code{"_preprocessed"} to \code{df}. Ignored if \code{remove = FALSE}.
#' @param datasources A list of \code{\link[DSI]{DSConnection-class}} objects.
#' If not provided, the default active connections are used.
#'
#' @return
#' \itemize{
#'   \item If \code{remove = TRUE}: invisibly returns a character string with the
#'   name of the created server-side object containing the filtered data. If no
#'   variables exceed the threshold, the original data are left unchanged and the
#'   intended output object name is still returned.
#'   \item If \code{remove = FALSE}:
#'   \itemize{
#'     \item For \code{type = "combined"}: a character vector of variables exceeding
#'     the threshold.
#'     \item For \code{type = "split"}: a named list of character vectors (one per
#'     server) containing variables exceeding the threshold.
#'     \item \code{NULL} if no variables exceed the threshold.
#'   }
#' }
#'
#' In every case above, the returned value additionally carries two attributes,
#' \code{"missing_aggregate"} and \code{"missing_server"}, as described in the
#' Description section, which can be retrieved via \code{attr()} (e.g.
#' \code{attr(result, "missing_aggregate")}).
#'
#' @export

ds.check_missing_data <- function(df,
                                  threshold,
                                  type = c("combined", "split"),
                                  remove = c(TRUE, FALSE),
                                  action = c("drop_column", "drop_rows"),
                                  preproc_newobj = NULL,
                                  datasources = NULL) {
  if (is.null(datasources))
    datasources <- datashield.connections_find()
  if (is.null(preproc_newobj))
    preproc_newobj <- paste0(df, "_preprocessed")

  type   <- match.arg(type)
  action <- match.arg(action)
  remove <- isTRUE(remove[1])

  server_fun <- if (action == "drop_rows") "drop_rows_missingDS" else "remove_columnsDS"

  # Compute % missing per server
  miss_list <- DSI::datashield.aggregate(
    conns = datasources,
    expr  = call("check_missing_dataDS", as.symbol(df))
  )

  # Servers need NOT have identical column sets or column ORDER: align by
  # NAME (union of columns across servers), never by position. A server
  # missing a column just gets NA for that column's missingness -- no error.
  # We only ever WARN (never stop) about a variable that is actually
  # REQUIRED (per the package's variable dictionary) but absent somewhere.
  all_cols <- sort(unique(unlist(lapply(miss_list, names))))

  required_vars <- tryCatch({
    dict <- DSI::datashield.aggregate(conns = datasources[1],
      expr = call("clinical_variable_dictionaryDS"))[[1]]
    dict$required
  }, error = function(e) character(0))

  missing_required <- setdiff(required_vars, all_cols)  # required vars absent at EVERY server
  for (srv in names(miss_list)) {
    srv_missing_req <- intersect(required_vars, setdiff(all_cols, names(miss_list[[srv]])))
    missing_required <- union(missing_required, srv_missing_req)
  }
  if (length(missing_required) > 0) {
    warning("Required variable(s) missing at one or more servers (treated as NA there, ",
            "not an error): ", paste(missing_required, collapse = ", "), call. = FALSE)
  }

  miss_tab <- as.data.frame(sapply(miss_list, function(x) x[all_cols]))
  rownames(miss_tab) <- all_cols
  colnames(miss_tab) <- names(datasources)

  .attach_tables <- function(x, aggregate = NULL, server = NULL) {
    attr(x, "missing_aggregate") <- aggregate
    attr(x, "missing_server")    <- server
    invisible(x)
  }

  # ── TYPE == COMBINED ──────────────────────────────────────────────────────
  if (type == "combined") {
    dims    <- dsBaseClient::ds.dim(df, type = "split", datasources = datasources)
    n_vec   <- sapply(dims, function(x) x[1])
    names(n_vec) <- names(dims)
    miss_mat <- as.matrix(sapply(miss_tab[, names(datasources), drop = FALSE], as.numeric))
    rownames(miss_mat) <- rownames(miss_tab)
    # Weighted average using only the servers where the variable actually
    # exists -- a variable absent at one server (NA there) must not poison
    # the whole row to NA via a plain matrix product.
    miss_tab$global <- apply(miss_mat, 1, function(row) {
      ok <- !is.na(row)
      if (!any(ok)) return(NA_real_)
      sum(row[ok] * n_vec[ok]) / sum(n_vec[ok])
    })

    missing_aggregate <- round(miss_tab, 2)

    vars_to_remove <- rownames(miss_tab)[!is.na(miss_tab$global) & miss_tab$global >= threshold]

    message("\n Missingness Table (%)")
    tbl_txt <- capture.output(round(miss_tab, 2))
    message(paste(tbl_txt, collapse = "\n"))
    message("\n Variables flagged (Global Missing >= ", threshold, "%)")

    if (length(vars_to_remove) == 0) {
      message("None")
      message("\nNo columns need to be removed")
      if (remove) {
        message("\n Preprocessed data stored as: ", preproc_newobj)
        return(.attach_tables(preproc_newobj, aggregate = missing_aggregate))
      }
      return(.attach_tables(NULL, aggregate = missing_aggregate))
    }

    removed_tab <- data.frame(
      variable       = vars_to_remove,
      global_missing = round(miss_tab[vars_to_remove, "global"], 2),
      row.names      = NULL
    )
    tbl_txt <- capture.output(removed_tab)
    message(paste(tbl_txt, collapse = "\n"))

    if (!remove) {
      message("\n remove = FALSE: no columns are removed.")
      return(.attach_tables(vars_to_remove, aggregate = missing_aggregate))
    }

    # remove = TRUE
    cols_string <- if (length(vars_to_remove) == 1) {
      paste0(vars_to_remove, "$")
    } else {
      paste(vars_to_remove, collapse = "$")
    }
    step_results <- DSI::datashield.aggregate(
      conns = datasources,
      expr  = call(server_fun, as.symbol(df), cols_string, preproc_newobj)
    )

    if (action == "drop_rows") {
      for (srv in names(step_results)) {
        message("  ", srv, ": removed ", step_results[[srv]]$n_removed, " of ",
                step_results[[srv]]$n_before, " rows (missing on flagged variable(s))")
      }
    } else {
      for (srv in names(step_results)) {
        message("  ", srv, ": removed columns -- ",
                paste(step_results[[srv]]$columns_removed, collapse = ", "))
      }
    }

    message("\n Preprocessed data stored as: ", preproc_newobj)
    return(.attach_tables(preproc_newobj, aggregate = missing_aggregate))
  }

  # ── TYPE == SPLIT ─────────────────────────────────────────────────────────
  if (type == "split") {
    message("\n Missingness Table (%)")
    tbl_txt <- capture.output(round(miss_tab, 2))
    message(paste(tbl_txt, collapse = "\n"))

    missing_server <- lapply(colnames(miss_tab), function(srv) {
      out <- data.frame(round(miss_tab[[srv]], 2), row.names = rownames(miss_tab))
      colnames(out) <- srv
      out
    })
    names(missing_server) <- colnames(miss_tab)

    vars_to_remove_list <- lapply(colnames(miss_tab), function(srv) {
      rownames(miss_tab)[!is.na(miss_tab[[srv]]) & miss_tab[[srv]] >= threshold]
    })
    names(vars_to_remove_list) <- colnames(miss_tab)

    message("\n Variables flagged per Server (Missing >= ", threshold, "%)")
    for (srv in names(vars_to_remove_list)) {
      message("\n ", srv, ":")
      vars_srv <- vars_to_remove_list[[srv]]
      if (length(vars_srv) == 0) {
        message("None")
      } else {
        removed_tab <- data.frame(
          variable    = vars_srv,
          missing_pct = round(miss_tab[vars_srv, srv], 2),
          row.names   = NULL
        )
        tbl_txt <- capture.output(removed_tab)
        message(paste(tbl_txt, collapse = "\n"))
      }
    }

    tot_removed <- sum(lengths(vars_to_remove_list))

    if (tot_removed == 0) {
      message("\nNo columns need to be removed")
      if (remove) {
        message("\n Preprocessed data stored as: ", preproc_newobj)
        return(.attach_tables(preproc_newobj, server = missing_server))
      }
      return(.attach_tables(NULL, server = missing_server))
    }

    if (!remove) {
      message("\n remove = FALSE: no columns are removed.")
      return(.attach_tables(vars_to_remove_list, server = missing_server))
    }

    # remove = TRUE: call remove_columnsDS per server
    for (srv in names(datasources)) {
      vars_srv <- vars_to_remove_list[[srv]]
      if (length(vars_srv) == 0)
        next
      cols_string <- if (length(vars_srv) == 1) {
        paste0(vars_srv, "$")
      } else {
        paste(vars_srv, collapse = "$")
      }
      step_result <- DSI::datashield.aggregate(
        conns = datasources[srv],
        expr  = call(server_fun, as.symbol(df), cols_string, preproc_newobj)
      )[[1]]

      if (action == "drop_rows") {
        message("  ", srv, ": removed ", step_result$n_removed, " of ",
                step_result$n_before, " rows (missing on flagged variable(s))")
      } else {
        message("  ", srv, ": removed columns -- ", paste(step_result$columns_removed, collapse = ", "))
      }
    }

    message("\n Preprocessed data stored as: ", preproc_newobj)
    return(.attach_tables(preproc_newobj, server = missing_server))
  }
}


