#' @title Dummy-encode ordinal DMARD-style variables on a server-side data frame
#' @description Adds integer 0/1 dummy columns for the specified ordinal/nominal
#'   variables (defaults to the DMARD family) while keeping the original
#'   column, itself coerced to integer. Uses the disclosure-safe server
#'   function \code{dummy_encode_ordinalDS}, called through
#'   \code{datashield.aggregate} -- the modified data frame is created
#'   server-side as a side effect; only column names come back.
#'   \code{IP_score} and \code{EP_score} are always excluded server-side even
#'   if included in \code{columns}, since those are severity annotations, not
#'   treatment categories.
#'
#' Server function called: \code{dummy_encode_ordinalDS}
#'
#' @param df A character string specifying the name of the server-side data frame.
#' @param columns A character vector of columns to dummy-encode. Defaults to
#'   \code{c("csDMARD1", "csDMARD2", "csDMARD3", "bDMARD", "tsDMARD", "GC_type")}.
#' @param newobj A character string specifying the name of the new server-side
#'   object. If NULL, a name is generated by appending \code{"_dummy"} to \code{df}.
#' @param datasources A list of \code{\link[DSI]{DSConnection-class}} objects.
#'   If not specified, the default set of connections is used.
#'
#' @return Invisibly returns the name of the newly created server-side object.
#' @export
ds.dummy_encode_ordinal <- function(df,
                                     columns = c("csDMARD1", "csDMARD2", "csDMARD3",
                                                 "bDMARD", "tsDMARD", "GC_type"),
                                     newobj = NULL, datasources = NULL) {

  if (is.null(datasources)) {
    datasources <- datashield.connections_find()
  }

  if (is.null(newobj)) {
    newobj <- paste0(df, "_dummy")
  }

  collapsed_columns <- paste(columns, collapse = "$")

  results <- DSI::datashield.aggregate(
    conns = datasources,
    expr  = call("dummy_encode_ordinalDS", as.symbol(df), collapsed_columns, newobj)
  )

  for (server in names(results)) {
    added <- results[[server]]$added
    skipped <- results[[server]]$skipped_excluded
    message("Server ", server, ": added dummy columns: ",
            if (length(added)) paste(added, collapse = ", ") else "none")
    if (length(skipped) > 0) {
      message("Server ", server, ": skipped (excluded by design): ",
              paste(skipped, collapse = ", "))
    }
  }

  message("Result saved as: '", newobj, "'")
  invisible(newobj)
}
